### ISSUE TITLE
Sabnzbd+Transmission-bt addons Support

### ISSUE THREAD

**Issue by Ntemis** [diego-vieira/ReadyNAS-Add-ons#1]
Am very interested in these two addons
http://sabnzbd.org/
http://www.transmissionbt.com/

**Comment by dv336699** [comment]
Awesome, I have started sabnzbd.
Since I have not used it in the past, give me a few to get used to it and be able to test it properly :)

**Comment by Ntemis** [comment]
So any news on this?
